name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install build tools
      run: |
        sudo apt-get update
        sudo apt-get install -y autoconf automake libtool

    - name: Build and Test
      # No working-directory needed if configure.ac is in the repo root
      run: |
        autoreconf -vfi
        ./configure
        make
        make check
        make distcheck


